name: RuneTest
version: '1.0-SNAPSHOT'
main: org.randomlima.runetest.RuneTest
api-version: '1.20'
commands:
  getrune:
    description: "Get a rune item"
    usage: "/getrune <rune name> <rune level>"
  getstaff:
    description: "Get a staff"
    usage: "/getstaff <staff name> <model data>"
